# action.yaml
name: Pristine Ubuntu
description: Remove the clutter from GitHub's hosted Ubuntu runners

inputs:
  keep-android:
    description: Keep Android SDK
    default: ''
  keep-chromedriver:
    description: Keep Chromedriver
    default: ''
  keep-rustup:
    description: Keep rustup
    default: ''
  keep-azure:
    description: Keep Azure CLI
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Delete Android SDK
      # https://github.com/actions/runner-images/blob/main/images/ubuntu/scripts/build/install-android-sdk.sh
      shell: bash
      id: android
      if: ${{ inputs.keep-android == '' }}
      run: |
        echo Deleting Android SDK
        sudo rm -rf /usr/local/lib/android &
    - name: Delete Chromedriver
      # https://github.com/actions/runner-images/blob/main/images/ubuntu/scripts/build/install-google-chrome.sh
      shell: bash
      id: chromedriver
      if: ${{ inputs.keep-chromedriver == '' }}
      run: |
        echo Deleting Chromedriver
        sudo rm -rf /usr/local/share/chromedriver-linux64 /usr/local/share/chromium &
    - name: Remove Julia
      # https://github.com/actions/runner-images/blob/main/images/ubuntu/scripts/build/install-julia.sh
      shell: bash
      run: |
        nohup sudo rm -rf /usr/local/julia* >& /dev/null &
        if [[ -L /usr/bin/julia ]]; then
          sudo rm /usr/bin/julia
        fi
    - name: Remove rustup
      # https://github.com/actions/runner-images/blob/main/images/ubuntu/scripts/build/install-rust.sh
      shell: bash
      id: rustup
      if: ${{ inputs.keep-rustup == '' }}
      run: |
        rm -rf ~/.cargo/bin ~/.rustup &
    - name: Remove Azure CLI
      # https://github.com/actions/runner-images/blob/main/images/ubuntu/scripts/build/install-azure-cli.sh
      # https://github.com/actions/runner-images/blob/main/images/ubuntu/scripts/build/install-azure-devops-cli.sh
      shell: bash
      if: ${{ inputs.keep-azure == '' }}
      id: azure-cli
      run: |
        # Only suppress "not installed" error, surface unexpected errors
        if ! sudo apt-get --yes purge azure-cli; then
          if ! apt list --installed 2>/dev/null | grep -q '^azure-cli/'; then
            echo "azure-cli not installed, ignoring error."
          else
            echo "Unexpected error removing azure-cli" >&2
            exit 1
          fi
        fi
        sudo rm -rf /opt/az ~/.azure
    - name: Uninstall Temurin Java (including ant)
      shell: bash
      id: temurin
      run: |
        echo "JAVA_HOME=" >> "${GITHUB_ENV}"
        sudo apt-get --yes purge temurin-* ant default-jre-headless
    - name: Remove Edge
      shell: bash
      id: edge
      run: |
        sudo apt-get --yes purge microsoft-edge-stable
    - name: Remove Firefox
      shell: bash
      id: firefox
      run: |
        sudo apt-get --yes purge firefox
    - name: Remove Chrome
      shell: bash
      id: chrome
      run: |
        sudo apt-get --yes purge google-chrome-stable
