# action.yaml
name: Pristine Ubuntu
description: Remove the clutter from GitHub's hosted Ubuntu runners
icon: thumbs-down
color: gray-dark

inputs:
  keep-android:
    description: Keep Android SDK
    default: ''
  keep-rustup:
    description: Keep rustup
    default: ''
  keep-azure:
    description: Keep Azure CLI
    default: ''
  keep-powershell:
    description: Keep Powershell
  keep-ansible:
    description: Keep Ansible
    default: ''
  keep-dotnet:
    description: Keep .NET Core SDK
    default: ''
  keep-haskell:
    description: Keep Haskell (GHCup, GHC, Cabal, Stack)
    default: ''
  keep-miniconda:
    description: Keep Miniconda
    default: ''
  keep-homebrew:
    description: Keep Homebrew
    default: ''
  keep-nginx:
    description: Keep Nginx
    default: ''
  keep-php:
    description: Keep PHP
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Delete Android SDK
      # https://github.com/actions/runner-images/blob/main/images/ubuntu/scripts/build/install-android-sdk.sh
      shell: bash
      id: android
      if: ${{ inputs.keep-android == '' }}
      run: |
        echo Deleting Android SDK
        sudo rm -rf /usr/local/lib/android &
    - name: Delete Chromedriver
      # https://github.com/actions/runner-images/blob/main/images/ubuntu/scripts/build/install-google-chrome.sh
      shell: bash
      id: chromedriver
      if: ${{ inputs.keep-chromedriver == '' }}
      run: |
        echo Deleting Chromedriver
        sudo rm -rf /usr/local/share/chromedriver-linux64 /usr/local/share/chromium &
    - name: Remove Julia
      # https://github.com/actions/runner-images/blob/main/images/ubuntu/scripts/build/install-julia.sh
      shell: bash
      run: |
        nohup sudo rm -rf /usr/local/julia* >& /dev/null &
        if [[ -L /usr/bin/julia ]]; then
          sudo rm /usr/bin/julia
        fi
    - name: Remove rustup
      # https://github.com/actions/runner-images/blob/main/images/ubuntu/scripts/build/install-rust.sh
      shell: bash
      id: rustup
      if: ${{ inputs.keep-rustup == '' }}
      run: |
        rm -rf ~/.cargo/bin ~/.rustup &
    - name: Remove Azure CLI
      # https://github.com/actions/runner-images/blob/main/images/ubuntu/scripts/build/install-azure-cli.sh
      # https://github.com/actions/runner-images/blob/main/images/ubuntu/scripts/build/install-azure-devops-cli.sh
      shell: bash
      if: ${{ inputs.keep-azure == '' }}
      id: azure-cli
      run: |
        # Only suppress "not installed" error, surface unexpected errors
        if ! sudo apt-get --yes purge azure-cli; then
          if ! apt list --installed 2>/dev/null | grep -q '^azure-cli/'; then
            echo "azure-cli not installed, ignoring error."
          else
            echo "Unexpected error removing azure-cli" >&2
            exit 1
          fi
        fi
        sudo rm -rf /opt/az ~/.azure
    - name: Uninstall Temurin Java (including ant)
      shell: bash
      id: temurin
      run: |
        echo "JAVA_HOME=" >> "${GITHUB_ENV}"
        sudo apt-get --yes purge temurin-* ant default-jre-headless
    - name: Remove browsers and Selenium
      # https://github.com/actions/runner-images/blob/main/images/ubuntu/scripts/build/install-firefox.sh
      # https://github.com/actions/runner-images/blob/main/images/ubuntu/scripts/build/install-google-chrome.sh
      # https://github.com/actions/runner-images/blob/main/images/ubuntu/scripts/build/install-microsoft-edge.sh
      shell: bash
      id: browsers
      run: |
        sudo rm -rf /usr/local/share/gecko_driver /usr/bin/geckodriver &
        sudo rm -rf /usr/local/share/chromedriver* /usr/bin/chromedriver /usr/local/share/chromium /usr/bin/chromium /usr/bin/chromium-browser &
        sudo rm -rf /usr/local/share/edge_driver /usr/bin/msedgedriver &
        sudo rm -rf /usr/share/java/selenium-server* &

        PACKAGES="microsoft-edge-stable firefox google-chrome-stable"
        for pkg in $PACKAGES; do
          # Only suppress "not installed" error, surface unexpected errors
          if ! sudo apt-get --yes purge "$pkg"; then
            if ! apt list --installed 2>/dev/null | grep -q "^$pkg/"; then
              echo "$pkg not installed, ignoring error."
            else
              echo "Unexpected error removing $pkg" >&2
              exit 1
            fi
          fi
        done
    - name: Delete Powershell
      # https://github.com/actions/runner-images/blob/main/images/ubuntu/scripts/build/install-powershell.sh
      shell: bash
      id: powershell
      if: ${{ inputs.keep-powershell == '' }}
      run: |
        sudo rm -rf /usr/local/share/powershell &
                # Only suppress "not installed" error, surface unexpected errors
        if ! sudo apt-get --yes purge powershell; then
          if ! apt list --installed 2>/dev/null | grep -q '^powershell/'; then
            echo "powershell not installed, ignoring error."
          else
            echo "Unexpected error removing powershell" >&2
            exit 1
          fi
        fi
        sudo rm -rf /usr/local/share/powershell
    - name: Remove ansible
      # https://github.com/actions/runner-images/blob/main/images/ubuntu/scripts/build/install-pipx-packages.sh
      shell: bash
      if: ${{ inputs.keep-ansible == '' }}
      id: ansible
      run: |
        sudo rm -rf /opt/pipx_bin/ansible* /opt/pipx/venvs/ansible-core &
    - name: Remove .NET Core SDK
      # https://github.com/actions/runner-images/blob/main/images/ubuntu/scripts/build/install-dotnetcore-sdk.sh
      shell: bash
      if: ${{ inputs.keep-dotnet == '' }}
      id: dotnet
      run: |
        echo "Removing .NET Core SDK"
        
        # Unset DOTNET environment variables
        echo "DOTNET_ROOT=" >> "${GITHUB_ENV}"
        echo "DOTNET_SKIP_FIRST_TIME_EXPERIENCE=" >> "${GITHUB_ENV}"
        echo "DOTNET_NOLOGO=" >> "${GITHUB_ENV}"
        echo "DOTNET_MULTILEVEL_LOOKUP=" >> "${GITHUB_ENV}"
        
        # Remove dotnet-sdk packages first
        DOTNET_PACKAGES=$(dpkg -l | grep -E '^ii\s+dotnet-sdk-' | awk '{print $2}' || true)
        if [ -n "$DOTNET_PACKAGES" ]; then
          for pkg in $DOTNET_PACKAGES; do
            # Only suppress "not installed" error, surface unexpected errors
            if ! sudo apt-get --yes purge "$pkg"; then
              if ! apt list --installed 2>/dev/null | grep -q "^$pkg/"; then
                echo "$pkg not installed, ignoring error."
              else
                echo "Unexpected error removing $pkg" >&2
                exit 1
              fi
            fi
          done
        fi
        
        # Remove directory after packages are purged
        sudo rm -rf /usr/share/dotnet &
    - name: Remove Haskell
      # https://github.com/actions/runner-images/blob/main/images/ubuntu/scripts/build/install-haskell.sh
      shell: bash
      if: ${{ inputs.keep-haskell == '' }}
      id: haskell
      run: |
        echo "Removing Haskell"
        sudo rm -rf /usr/local/.ghcup ~/.ghcup ~/.cabal &
        # Remove binaries from PATH
        sudo rm -f /usr/local/bin/ghc* /usr/local/bin/cabal /usr/local/bin/stack /usr/local/bin/haskell-language-server* &
    - name: Remove Miniconda
      # https://github.com/actions/runner-images/blob/main/images/ubuntu/scripts/build/install-miniconda.sh
      shell: bash
      if: ${{ inputs.keep-miniconda == '' }}
      id: miniconda
      run: |
        echo "Removing Miniconda"
        sudo rm -rf /usr/share/miniconda &
        sudo rm -f /usr/bin/conda &
    - name: Remove Homebrew
      # https://github.com/actions/runner-images/blob/main/images/ubuntu/scripts/build/install-homebrew.sh
      shell: bash
      if: ${{ inputs.keep-homebrew == '' }}
      id: homebrew
      run: |
        echo "Removing Homebrew"
        sudo rm -rf /home/linuxbrew/.linuxbrew &
    - name: Remove Nginx
      # https://github.com/actions/runner-images/blob/main/images/ubuntu/scripts/build/install-nginx.sh
      shell: bash
      if: ${{ inputs.keep-nginx == '' }}
      id: nginx
      run: |
        echo "Removing Nginx"
        # Only suppress "not installed" error, surface unexpected errors
        if ! sudo apt-get --yes purge nginx nginx-common nginx-core; then
          if ! apt list --installed 2>/dev/null | grep -q '^nginx'; then
            echo "nginx not installed, ignoring error."
          else
            echo "Unexpected error removing nginx" >&2
            exit 1
          fi
        fi
        sudo rm -rf /etc/nginx
    - name: Remove PHP
      # https://github.com/actions/runner-images/blob/main/images/ubuntu/scripts/build/install-php.sh
      shell: bash
      if: ${{ inputs.keep-php == '' }}
      id: php
      run: |
        echo "Removing PHP"
        # Find and purge PHP packages
        PHP_PACKAGES=$(dpkg -l | grep -E '^ii\s+(php|libapache2-mod-php|composer|phive)' | awk '{print $2}' || true)
        if [ -n "$PHP_PACKAGES" ]; then
          for pkg in $PHP_PACKAGES; do
            # Only suppress "not installed" error, surface unexpected errors
            if ! sudo apt-get --yes purge "$pkg"; then
              if ! apt list --installed 2>/dev/null | grep -q "^$pkg/"; then
                echo "$pkg not installed, ignoring error."
              else
                echo "Unexpected error removing $pkg" >&2
                exit 1
              fi
            fi
          done
        fi
        sudo rm -rf /etc/php /usr/lib/php /usr/bin/php* /usr/sbin/php* ~/.config/composer ~/.phive
