# action.yaml
name: Pristine Ubuntu
description: Remove the clutter from GitHub's hosted Ubuntu runners

inputs:
  keep-android:
    description: Opt into keeping the Android SDK
    type: boolean
    default: ''

runs:
  using: 'composite'
  steps:
    - name: File deletions
      # https://github.com/actions/runner-images/blob/main/images/ubuntu/scripts/build/install-android-sdk.sh
      shell: bash
      id: delete-files
      if: ${{ inputs.keep-android != false }}
      run: |
        if [[ ${{ inputs.keep-android }} != '' ]]; then
          sudo rm -rf /usr/local/lib/android &
        fi
        sudo rm -rf /usr/local/share/chromedriver-linux64 /usr/local/share/chromium &

        while fg; do true; done
    - name: Remove Julia
      # https://github.com/actions/runner-images/blob/main/images/ubuntu/scripts/build/install-julia.sh
      shell: bash
      run: |
        nohup sudo rm -rf /usr/local/julia* >& /dev/null &
        if [[ -L /usr/bin/julia ]]; then
          sudo rm /usr/bin/julia
        fi
    - name: Uninstall Temurin Java (including ant)
      shell: bash
      id: temurin
      run: |
        echo "JAVA_HOME=" >> "${GITHUB_ENV}"
        sudo apt-get --yes purge temurin-* ant default-jre-headless


