# action.yaml
name: Pristine Ubuntu
description: Remove the clutter from GitHub's hosted Ubuntu runners

inputs:
  keep-android:
    description: Opt into keeping the Android SDK. (Any non-empty value)
    default: ''
  keep-chromedriver:
    description: Opt into keeping Chromedriver. (Any non-empty value)
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Delete Android SDK
      # https://github.com/actions/runner-images/blob/main/images/ubuntu/scripts/build/install-android-sdk.sh
      shell: bash
      id: android
      if: ${{ inputs.keep-android == '' }}
      run: |
        echo Deleting Android SDK
        sudo rm -rf /usr/local/lib/android &
    - name: Delete Chromedriver
      shell: bash
      id: chromedriver
      if: ${{ inputs.keep-chromedriver == '' }}
      run: |
        echo Deleting Chromedriver
        sudo rm -rf /usr/local/share/chromedriver-linux64 /usr/local/share/chromium &
    - name: Remove Julia
      # https://github.com/actions/runner-images/blob/main/images/ubuntu/scripts/build/install-julia.sh
      shell: bash
      run: |
        nohup sudo rm -rf /usr/local/julia* >& /dev/null &
        if [[ -L /usr/bin/julia ]]; then
          sudo rm /usr/bin/julia
        fi
    - name: Uninstall Temurin Java (including ant)
      shell: bash
      id: temurin
      run: |
        echo "JAVA_HOME=" >> "${GITHUB_ENV}"
        sudo apt-get --yes purge temurin-* ant default-jre-headless


