# action.yaml
name: Pristine Ubuntu
description: Remove the clutter from GitHub's hosted Ubuntu runners
runs:
  using: 'composite'
  steps:
    - name: Delete the Android SDK
      shell: bash
      id: android-sdk
      run: |
        nohup sudo rm -rf /usr/local/lib/android/ >& /dev/null &
    - name: Delete local binaries
      shell: bash
      id: local-bins
      run: |
        nohup sudo rm -f /usr/local/bin/* >& /dev/null &
    - name: Uninstall Temurin Java
      shell: bash
      run: |
        echo "JAVA_HOME=" >> "${GITHUB_ENV}"
        sudo apt-get --yes purge temurin-*

